export const SET_LINE_WEIGHT = 'SET_LINE_WEIGHT';
export const SET_LINE_COLOR = 'SET_LINE_COLOR';
export const SET_INSTRUMENT = 'SET_INSTRUMENT';

export const SET_CANVAS_SIZE = 'SET_CANVAS_SIZE';

export const SET_MOUSE_DOWN_POSITION = 'SET_MOUSE_DOWN_POSITION';

export const SET_MAIN_CTX = 'SET_MAIN_CTX';
export const SET_SUB_CTX = 'SET_SUB_CTX';

export const SET_DATA_URL = 'SET_DATA_URL';

export const UPLOAD_IMAGE_SUCCEEDED = 'UPLOAD_IMAGE_SUCCEEDED';
export const UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED';


export const CREATE_USER_WITH_E_MAIL: string = 'CREATE_USER_WITH_E_MAIL';
export const CREATE_USER_WITH_E_MAIL_SUCCEEDED: string = 'CREATE_USER_WITH_E_MAIL_SUCCEEDED';
export const CREATE_USER_WITH_E_MAIL_FAILED: string = 'CREATE_USER_WITH_E_MAIL_FAILED';

export const SIGN_IN_WITH_E_MAIL: string = 'SIGN_IN_WITH_E_MAIL';
export const SIGN_IN_WITH_E_MAIL_SUCCEEDED: string = 'SIGN_IN_WITH_E_MAIL_SUCCEEDED';
export const SIGN_IN_WITH_E_MAIL_FAILED: string = 'SIGN_IN_WITH_E_MAIL_FAILED';

export const SIGN_OUT: string = 'SIGN_OUT';

export const CHECK_USER_AFTORIZATION: string = 'CHECK_USER_AFTORIZATION';