export const SET_LINE_WEIGHT: string = 'SET_LINE_WEIGHT';
export const SET_LINE_COLOR: string = 'SET_LINE_COLOR';
export const SET_INSTRUMENT: string = 'SET_INSTRUMENT';
export const SET_CANVAS_SIZE: string = 'SET_CANVAS_SIZE';
export const SET_MOUSE_DOWN_POSITION: string = 'SET_MOUSE_DOWN_POSITION';
export const SET_MAIN_CTX: string = 'SET_MAIN_CTX';
export const SET_SUB_CTX: string = 'SET_SUB_CTX';
export const SET_DATA_URL: string = 'SET_DATA_URL';
export const UPLOAD_IMAGE_SUCCEEDED: string = 'UPLOAD_IMAGE_SUCCEEDED';
export const UPLOAD_IMAGE_FAILED: string = 'UPLOAD_IMAGE_FAILED';
export const OPEN_UPLOAD_WINDOW: string = 'OPEN_UPLOAD_WINDOW';

export const CREATE_USER_WITH_E_MAIL: string = 'CREATE_USER_WITH_E_MAIL';
export const CREATE_USER_WITH_E_MAIL_SUCCEEDED: string = 'CREATE_USER_WITH_E_MAIL_SUCCEEDED';
export const CREATE_USER_WITH_E_MAIL_FAILED: string = 'CREATE_USER_WITH_E_MAIL_FAILED';
export const SIGN_IN_WITH_E_MAIL: string = 'SIGN_IN_WITH_E_MAIL';
export const SIGN_IN_WITH_E_MAIL_SUCCEEDED: string = 'SIGN_IN_WITH_E_MAIL_SUCCEEDED';
export const SIGN_IN_WITH_E_MAIL_FAILED: string = 'SIGN_IN_WITH_E_MAIL_FAILED';
export const SIGN_OUT: string = 'SIGN_OUT';
export const CHECK_USER_AFTORIZATION: string = 'CHECK_USER_AFTORIZATION';
export const RESET_ERROR_MESSAGE: string = 'RESET_ERROR_MESSAGE';
export const SET_LOCAL_USER_ERROR_MESSAGE: string = 'SET_LOCAL_USER_ERROR_MESSAGE';
 
export const GET_IMAGES_FROM_DB: string = 'GET_IMAGES_FROM_DB';
export const GET_IMAGES_FROM_DB_SUCCEEDED: string = 'GET_IMAGES_FROM_DB_SUCCEEDED';
export const GET_IMAGES_FROM_DB_FAILED: string = 'GET_IMAGES_FROM_DB_FAILED';
export const SORT_IMAGES_DATA: string = 'SORT_IMAGES_DATA';

export const GET_USER_NAME: string = 'GET_USER_NAME';
export const GET_USER_IMAGES_FROM_DB: string = 'GET_USER_IMAGES_FROM_DB';
export const GET_USER_IMAGES_FROM_DB_SUCCEEDED: string = 'GET_USER_IMAGES_FROM_DB_SUCCEEDED';
export const GET_USER_IMAGES_FROM_DB_FAILED: string = 'GET_USER_IMAGES_FROM_DB_FAILED';
export const DEL_CLICKED: string = 'DEL_CLICKED';
export const DEL_USER_IMAGE_FROM_DB: string = 'DEL_USER_IMAGE_FROM_DB';
export const DEL_USER_IMAGE_FROM_DB_SUCCEEDED: string = 'DEL_USER_IMAGE_FROM_DB_SUCCEEDED';
export const DEL_USER_IMAGE_FROM_DB_FAILED: string = 'DEL_USER_IMAGE_FROM_DB_FAILED';